spring:
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:events_db
    username: admin
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format_sql: true